### ISSUE TITLE
Dataset and trained model

### ISSUE THREAD

**Issue by A7ocin** [rollervan/BCN_3DPose#1]
Hello, thank you for making the code for the paper available. I was wondering if it was possible to have a link for the training dataset and/or the trained model.

Thank you

**Comment by rollervan** [comment]
Hello, thank you for your interest. Both will be available as soon as possible. 

I'll let you now.

Thanks

**Comment by rollervan** [comment]
@A7ocin Now you can download both. 

Thank you
